/**
 * Static, curated SQL intelligence data.
 * Kept as compact tuples so the bundled size stays tiny; CompletionItems
 * are built lazily on first use and cached (see completion.ts).
 */

/** [name, signature, one-line doc, return type] */
export type FnDoc = readonly [string, string, string, string];

export const COMMON_KEYWORDS: string[] = [
  'SELECT', 'FROM', 'WHERE', 'GROUP BY', 'ORDER BY', 'HAVING', 'DISTINCT',
  'INSERT INTO', 'UPDATE', 'DELETE FROM', 'VALUES', 'SET',
  'INNER JOIN', 'LEFT JOIN', 'RIGHT JOIN', 'FULL OUTER JOIN', 'CROSS JOIN', 'ON',
  'AS', 'AND', 'OR', 'NOT', 'IN', 'EXISTS', 'BETWEEN', 'LIKE',
  'IS NULL', 'IS NOT NULL', 'ASC', 'DESC', 'UNION', 'UNION ALL', 'ANY', 'ALL',
  'CASE', 'WHEN', 'THEN', 'ELSE', 'END', 'WITH',
  'CREATE TABLE', 'ALTER TABLE', 'DROP TABLE', 'TRUNCATE TABLE', 'CREATE INDEX', 'CREATE VIEW',
  'PRIMARY KEY', 'FOREIGN KEY', 'REFERENCES', 'CONSTRAINT', 'DEFAULT', 'UNIQUE', 'CHECK',
  'BEGIN', 'COMMIT', 'ROLLBACK',
  'OVER', 'PARTITION BY', 'ROWS BETWEEN', 'UNBOUNDED PRECEDING', 'CURRENT ROW',
  'OFFSET', 'FETCH NEXT',
];

export const PG_KEYWORDS: string[] = [
  'LIMIT', 'ILIKE', 'RETURNING', 'LATERAL', 'USING',
  'ON CONFLICT', 'DO NOTHING', 'DO UPDATE', 'EXPLAIN', 'EXPLAIN ANALYZE',
  'VACUUM', 'ANALYZE', 'GENERATED ALWAYS AS IDENTITY', 'SERIAL', 'TABLESAMPLE',
];

export const MSSQL_KEYWORDS: string[] = [
  'TOP', 'OUTPUT', 'MERGE', 'GO', 'USE', 'EXEC', 'DECLARE',
  'PIVOT', 'UNPIVOT', 'CROSS APPLY', 'OUTER APPLY', 'WITH (NOLOCK)',
  'IDENTITY', 'IF EXISTS', 'PRINT',
];

/**
 * Single-word tokens that get auto-UPPERCASED as you type (see keywordCase.ts).
 * Deliberately keywords only — never function names.
 */
export const UPPERCASE_TOKENS: string[] = [
  'SELECT', 'FROM', 'WHERE', 'AND', 'OR', 'NOT', 'NULL', 'IS', 'IN', 'EXISTS',
  'BETWEEN', 'LIKE', 'ILIKE', 'AS', 'ON', 'JOIN', 'INNER', 'LEFT', 'RIGHT',
  'FULL', 'OUTER', 'CROSS', 'GROUP', 'BY', 'ORDER', 'HAVING', 'DISTINCT',
  'UNION', 'ALL', 'ANY', 'CASE', 'WHEN', 'THEN', 'ELSE', 'END', 'WITH',
  'INSERT', 'INTO', 'VALUES', 'UPDATE', 'SET', 'DELETE', 'CREATE', 'ALTER',
  'DROP', 'TABLE', 'INDEX', 'VIEW', 'PRIMARY', 'KEY', 'FOREIGN', 'REFERENCES',
  'CONSTRAINT', 'DEFAULT', 'UNIQUE', 'CHECK', 'ASC', 'DESC', 'LIMIT', 'OFFSET',
  'FETCH', 'NEXT', 'ROWS', 'ONLY', 'TOP', 'OVER', 'PARTITION', 'RETURNING',
  'LATERAL', 'USING', 'MERGE', 'DECLARE', 'BEGIN', 'COMMIT', 'ROLLBACK',
  'TRUNCATE', 'EXEC', 'USE', 'GO', 'IF', 'WHILE', 'APPLY', 'PIVOT', 'UNPIVOT',
  'CALL', 'EXPLAIN',
];

export const PG_FUNCTIONS: FnDoc[] = [
  // Aggregates
  ['count', 'count(expression)', 'Number of input rows for which expression is not null; count(*) counts all rows.', 'bigint'],
  ['sum', 'sum(expression)', 'Sum of expression across all input rows.', 'numeric / bigint'],
  ['avg', 'avg(expression)', 'Average (arithmetic mean) of expression.', 'numeric'],
  ['min', 'min(expression)', 'Minimum value of expression.', 'same as input'],
  ['max', 'max(expression)', 'Maximum value of expression.', 'same as input'],
  ['array_agg', 'array_agg(expression)', 'Collects all input values into an array.', 'anyarray'],
  ['string_agg', "string_agg(expression, delimiter)", 'Concatenates values into a string separated by delimiter.', 'text'],
  ['json_agg', 'json_agg(expression)', 'Aggregates values into a JSON array.', 'json'],
  ['jsonb_agg', 'jsonb_agg(expression)', 'Aggregates values into a JSONB array.', 'jsonb'],
  ['json_object_agg', 'json_object_agg(key, value)', 'Aggregates key/value pairs into a JSON object.', 'json'],
  ['bool_and', 'bool_and(expression)', 'True if all input values are true.', 'boolean'],
  ['bool_or', 'bool_or(expression)', 'True if at least one input value is true.', 'boolean'],
  ['stddev', 'stddev(expression)', 'Sample standard deviation of the input values.', 'numeric'],
  ['variance', 'variance(expression)', 'Sample variance of the input values.', 'numeric'],
  ['percentile_cont', 'percentile_cont(fraction) WITHIN GROUP (ORDER BY expr)', 'Continuous percentile — interpolated value at the given fraction.', 'double precision / interval'],
  ['percentile_disc', 'percentile_disc(fraction) WITHIN GROUP (ORDER BY expr)', 'Discrete percentile — first value whose position equals or exceeds the fraction.', 'same as expr'],
  ['mode', 'mode() WITHIN GROUP (ORDER BY expr)', 'Most frequent input value.', 'same as expr'],
  // String
  ['length', 'length(string)', 'Number of characters in string.', 'integer'],
  ['char_length', 'char_length(string)', 'Number of characters in string.', 'integer'],
  ['lower', 'lower(string)', 'Converts string to lower case.', 'text'],
  ['upper', 'upper(string)', 'Converts string to upper case.', 'text'],
  ['initcap', 'initcap(string)', 'Capitalizes the first letter of each word.', 'text'],
  ['trim', "trim([leading|trailing|both] chars from string)", 'Removes leading/trailing characters (spaces by default).', 'text'],
  ['ltrim', 'ltrim(string, chars)', 'Removes characters from the start of string.', 'text'],
  ['rtrim', 'rtrim(string, chars)', 'Removes characters from the end of string.', 'text'],
  ['btrim', 'btrim(string, chars)', 'Removes characters from both ends of string.', 'text'],
  ['lpad', 'lpad(string, length, fill)', 'Pads string on the left to length using fill.', 'text'],
  ['rpad', 'rpad(string, length, fill)', 'Pads string on the right to length using fill.', 'text'],
  ['substring', 'substring(string from start for count)', 'Extracts a substring (also substring(string, start, count)).', 'text'],
  ['substr', 'substr(string, start, count)', 'Extracts a substring.', 'text'],
  ['position', 'position(substring in string)', '1-based location of substring, 0 if not found.', 'integer'],
  ['strpos', 'strpos(string, substring)', '1-based location of substring, 0 if not found.', 'integer'],
  ['replace', 'replace(string, from, to)', 'Replaces all occurrences of a substring.', 'text'],
  ['translate', 'translate(string, from, to)', 'Replaces each character in from with the matching character in to.', 'text'],
  ['concat', 'concat(str1, str2, ...)', 'Concatenates arguments, ignoring NULLs.', 'text'],
  ['concat_ws', 'concat_ws(separator, str1, str2, ...)', 'Concatenates with separator, ignoring NULLs.', 'text'],
  ['split_part', 'split_part(string, delimiter, n)', 'Splits string on delimiter and returns the n-th field.', 'text'],
  ['left', 'left(string, n)', 'First n characters of string.', 'text'],
  ['right', 'right(string, n)', 'Last n characters of string.', 'text'],
  ['repeat', 'repeat(string, n)', 'Repeats string n times.', 'text'],
  ['reverse', 'reverse(string)', 'Reverses the string.', 'text'],
  ['regexp_replace', 'regexp_replace(string, pattern, replacement, flags)', 'Replaces substrings matching a POSIX regex.', 'text'],
  ['regexp_matches', 'regexp_matches(string, pattern, flags)', 'Returns captured substrings from a regex match (set-returning).', 'setof text[]'],
  ['regexp_split_to_array', 'regexp_split_to_array(string, pattern)', 'Splits string on a regex into an array.', 'text[]'],
  ['regexp_split_to_table', 'regexp_split_to_table(string, pattern)', 'Splits string on a regex into rows.', 'setof text'],
  ['format', "format(formatstr, args...)", 'sprintf-style string formatting (%s, %I identifier, %L literal).', 'text'],
  ['md5', 'md5(string)', 'MD5 hash of string as hex.', 'text'],
  ['to_hex', 'to_hex(number)', 'Converts a number to its hex representation.', 'text'],
  ['ascii', 'ascii(char)', 'Code point of the first character.', 'integer'],
  ['chr', 'chr(code)', 'Character with the given code point.', 'text'],
  ['quote_ident', 'quote_ident(string)', 'Quotes a string for use as an identifier.', 'text'],
  ['quote_literal', 'quote_literal(value)', 'Quotes a value for use as a string literal.', 'text'],
  ['starts_with', 'starts_with(string, prefix)', 'True if string begins with prefix.', 'boolean'],
  // Math
  ['abs', 'abs(x)', 'Absolute value.', 'same as input'],
  ['ceil', 'ceil(x)', 'Smallest integer >= x.', 'numeric'],
  ['floor', 'floor(x)', 'Largest integer <= x.', 'numeric'],
  ['round', 'round(x, s)', 'Rounds x to s decimal places.', 'numeric'],
  ['trunc', 'trunc(x, s)', 'Truncates x toward zero to s decimal places.', 'numeric'],
  ['sign', 'sign(x)', '-1, 0, or +1 depending on the sign of x.', 'numeric'],
  ['sqrt', 'sqrt(x)', 'Square root.', 'double precision'],
  ['cbrt', 'cbrt(x)', 'Cube root.', 'double precision'],
  ['power', 'power(a, b)', 'a raised to the power b.', 'double precision'],
  ['exp', 'exp(x)', 'e raised to x.', 'double precision'],
  ['ln', 'ln(x)', 'Natural logarithm.', 'double precision'],
  ['log', 'log(b, x)', 'Logarithm of x to base b (log(x) is base 10).', 'numeric'],
  ['mod', 'mod(y, x)', 'Remainder of y / x.', 'same as input'],
  ['pi', 'pi()', 'The constant π.', 'double precision'],
  ['random', 'random()', 'Random value in [0, 1).', 'double precision'],
  ['degrees', 'degrees(radians)', 'Radians to degrees.', 'double precision'],
  ['radians', 'radians(degrees)', 'Degrees to radians.', 'double precision'],
  ['gcd', 'gcd(a, b)', 'Greatest common divisor.', 'same as input'],
  ['width_bucket', 'width_bucket(operand, low, high, count)', 'Bucket number for operand in an equal-width histogram.', 'integer'],
  // Date / time
  ['now', 'now()', 'Current date and time (start of transaction).', 'timestamptz'],
  ['current_date', 'current_date → date', 'Current date (no parentheses).', 'date'],
  ['current_timestamp', 'current_timestamp → timestamptz', 'Current date and time (no parentheses).', 'timestamptz'],
  ['clock_timestamp', 'clock_timestamp()', 'Actual current time — changes within a statement.', 'timestamptz'],
  ['age', 'age(timestamp, timestamp)', 'Symbolic interval between two timestamps (or from now()).', 'interval'],
  ['date_part', "date_part('field', source)", 'Extracts a subfield (year, month, dow, epoch, ...) as float.', 'double precision'],
  ['date_trunc', "date_trunc('field', source)", 'Truncates to the given precision (hour, day, month, ...).', 'timestamp / timestamptz'],
  ['extract', 'extract(field from source)', 'Extracts a subfield from a date/time value.', 'numeric'],
  ['to_char', 'to_char(value, format)', 'Formats a timestamp/number as text (e.g. YYYY-MM-DD).', 'text'],
  ['to_date', 'to_date(text, format)', 'Parses text into a date using a format.', 'date'],
  ['to_timestamp', 'to_timestamp(text, format)', 'Parses text into a timestamp (or converts a Unix epoch).', 'timestamptz'],
  ['to_number', 'to_number(text, format)', 'Parses text into a numeric using a format.', 'numeric'],
  ['make_date', 'make_date(year, month, day)', 'Builds a date from parts.', 'date'],
  ['make_interval', 'make_interval(years, months, weeks, days, hours, mins, secs)', 'Builds an interval from parts.', 'interval'],
  ['make_timestamp', 'make_timestamp(year, month, day, hour, min, sec)', 'Builds a timestamp from parts.', 'timestamp'],
  ['generate_series', 'generate_series(start, stop, step)', 'Generates a set of values from start to stop (numbers or timestamps).', 'setof same as start'],
  ['pg_sleep', 'pg_sleep(seconds)', 'Pauses the current session.', 'void'],
  // Conditional
  ['coalesce', 'coalesce(value, ...)', 'First non-null argument.', 'same as arguments'],
  ['nullif', 'nullif(value1, value2)', 'NULL if the two values are equal, else value1.', 'same as value1'],
  ['greatest', 'greatest(value, ...)', 'Largest of the arguments.', 'same as arguments'],
  ['least', 'least(value, ...)', 'Smallest of the arguments.', 'same as arguments'],
  // JSON
  ['to_json', 'to_json(anyelement)', 'Converts a value to JSON.', 'json'],
  ['to_jsonb', 'to_jsonb(anyelement)', 'Converts a value to JSONB.', 'jsonb'],
  ['row_to_json', 'row_to_json(record)', 'Converts a row to a JSON object.', 'json'],
  ['json_build_object', 'json_build_object(key, value, ...)', 'Builds a JSON object from alternating key/value arguments.', 'json'],
  ['jsonb_build_object', 'jsonb_build_object(key, value, ...)', 'Builds a JSONB object from alternating key/value arguments.', 'jsonb'],
  ['json_build_array', 'json_build_array(value, ...)', 'Builds a JSON array from arguments.', 'json'],
  ['jsonb_set', 'jsonb_set(target, path, new_value, create_missing)', 'Replaces the value at path in a JSONB document.', 'jsonb'],
  ['jsonb_pretty', 'jsonb_pretty(jsonb)', 'Formats JSONB as indented text.', 'text'],
  ['jsonb_array_length', 'jsonb_array_length(jsonb)', 'Number of elements in the top-level JSONB array.', 'integer'],
  ['jsonb_each', 'jsonb_each(jsonb)', 'Expands a JSONB object into key/value rows.', 'setof (key text, value jsonb)'],
  ['jsonb_object_keys', 'jsonb_object_keys(jsonb)', 'Returns the keys of a JSONB object as rows.', 'setof text'],
  ['jsonb_extract_path_text', 'jsonb_extract_path_text(jsonb, path...)', 'Extracts a nested value as text.', 'text'],
  // Arrays
  ['array_length', 'array_length(array, dimension)', 'Length of the array in the given dimension.', 'integer'],
  ['cardinality', 'cardinality(array)', 'Total number of elements in the array.', 'integer'],
  ['array_append', 'array_append(array, element)', 'Appends an element to an array.', 'anyarray'],
  ['array_cat', 'array_cat(array1, array2)', 'Concatenates two arrays.', 'anyarray'],
  ['array_remove', 'array_remove(array, element)', 'Removes all occurrences of element.', 'anyarray'],
  ['array_position', 'array_position(array, element)', 'Index of the first occurrence of element.', 'integer'],
  ['array_to_string', 'array_to_string(array, delimiter)', 'Joins array elements into a string.', 'text'],
  ['string_to_array', 'string_to_array(string, delimiter)', 'Splits a string into an array.', 'text[]'],
  ['unnest', 'unnest(array)', 'Expands an array into rows.', 'setof element type'],
  // Window
  ['row_number', 'row_number() OVER (...)', 'Sequential row number within the partition.', 'bigint'],
  ['rank', 'rank() OVER (...)', 'Rank with gaps for ties.', 'bigint'],
  ['dense_rank', 'dense_rank() OVER (...)', 'Rank without gaps.', 'bigint'],
  ['percent_rank', 'percent_rank() OVER (...)', 'Relative rank: (rank − 1) / (rows − 1).', 'double precision'],
  ['cume_dist', 'cume_dist() OVER (...)', 'Cumulative distribution of the current row.', 'double precision'],
  ['ntile', 'ntile(buckets) OVER (...)', 'Splits the partition into N ranked buckets.', 'integer'],
  ['lag', 'lag(value, offset, default) OVER (...)', 'Value from a preceding row in the partition.', 'same as value'],
  ['lead', 'lead(value, offset, default) OVER (...)', 'Value from a following row in the partition.', 'same as value'],
  ['first_value', 'first_value(value) OVER (...)', 'Value from the first row of the window frame.', 'same as value'],
  ['last_value', 'last_value(value) OVER (...)', 'Value from the last row of the window frame.', 'same as value'],
  ['nth_value', 'nth_value(value, n) OVER (...)', 'Value from the n-th row of the window frame.', 'same as value'],
  // System / misc
  ['gen_random_uuid', 'gen_random_uuid()', 'Random UUID (v4).', 'uuid'],
  ['version', 'version()', 'PostgreSQL server version string.', 'text'],
  ['current_database', 'current_database()', 'Name of the current database.', 'name'],
  ['current_schema', 'current_schema()', 'Name of the current schema.', 'name'],
  ['current_user', 'current_user → name', 'Current user name (no parentheses).', 'name'],
  ['pg_typeof', 'pg_typeof(any)', 'Data type of the argument.', 'regtype'],
  ['pg_size_pretty', 'pg_size_pretty(bigint)', 'Formats bytes as a human-readable size.', 'text'],
  ['pg_total_relation_size', "pg_total_relation_size('table')", 'Total disk space used by a table, incl. indexes and TOAST.', 'bigint'],
  ['pg_database_size', "pg_database_size('name')", 'Disk space used by a database.', 'bigint'],
  ['cast', 'cast(expression AS type)', 'Converts a value to another data type (also expr::type).', 'target type'],
];

export const MSSQL_FUNCTIONS: FnDoc[] = [
  // Aggregates
  ['COUNT', 'COUNT(expression)', 'Number of items in a group; COUNT(*) counts all rows.', 'int'],
  ['COUNT_BIG', 'COUNT_BIG(expression)', 'Like COUNT but returns bigint.', 'bigint'],
  ['SUM', 'SUM(expression)', 'Sum of all values in the expression.', 'same as expression'],
  ['AVG', 'AVG(expression)', 'Average of the values in a group.', 'same as expression'],
  ['MIN', 'MIN(expression)', 'Minimum value in the expression.', 'same as expression'],
  ['MAX', 'MAX(expression)', 'Maximum value in the expression.', 'same as expression'],
  ['STRING_AGG', "STRING_AGG(expression, separator)", 'Concatenates values with a separator (ORDER BY via WITHIN GROUP).', 'nvarchar'],
  ['STDEV', 'STDEV(expression)', 'Sample standard deviation.', 'float'],
  ['VAR', 'VAR(expression)', 'Sample variance.', 'float'],
  ['APPROX_COUNT_DISTINCT', 'APPROX_COUNT_DISTINCT(expression)', 'Fast approximate distinct count for big data.', 'bigint'],
  ['GROUPING', 'GROUPING(column)', '1 when the column is aggregated by ROLLUP/CUBE, else 0.', 'tinyint'],
  ['CHECKSUM_AGG', 'CHECKSUM_AGG(expression)', 'Checksum of the values in a group.', 'int'],
  // String
  ['LEN', 'LEN(string)', 'Number of characters, excluding trailing spaces.', 'int / bigint'],
  ['DATALENGTH', 'DATALENGTH(expression)', 'Number of bytes used by the expression.', 'int / bigint'],
  ['LOWER', 'LOWER(string)', 'Converts to lower case.', 'same as input'],
  ['UPPER', 'UPPER(string)', 'Converts to upper case.', 'same as input'],
  ['LTRIM', 'LTRIM(string)', 'Removes leading spaces.', 'same as input'],
  ['RTRIM', 'RTRIM(string)', 'Removes trailing spaces.', 'same as input'],
  ['TRIM', "TRIM(characters FROM string)", 'Removes leading and trailing spaces (or given characters).', 'varchar / nvarchar'],
  ['SUBSTRING', 'SUBSTRING(string, start, length)', 'Extracts part of a string (1-based).', 'same as input'],
  ['CHARINDEX', 'CHARINDEX(substring, string, start)', '1-based position of substring, 0 if not found.', 'int / bigint'],
  ['PATINDEX', "PATINDEX('%pattern%', string)", 'Position of the first match of a pattern.', 'int / bigint'],
  ['REPLACE', 'REPLACE(string, from, to)', 'Replaces all occurrences of a substring.', 'varchar / nvarchar'],
  ['TRANSLATE', 'TRANSLATE(string, from_chars, to_chars)', 'Replaces characters one-for-one.', 'same as input'],
  ['STUFF', 'STUFF(string, start, length, replaceWith)', 'Deletes length chars at start and inserts replacement.', 'same as input'],
  ['LEFT', 'LEFT(string, n)', 'First n characters.', 'varchar / nvarchar'],
  ['RIGHT', 'RIGHT(string, n)', 'Last n characters.', 'varchar / nvarchar'],
  ['REPLICATE', 'REPLICATE(string, n)', 'Repeats string n times.', 'same as input'],
  ['REVERSE', 'REVERSE(string)', 'Reverses the string.', 'varchar / nvarchar'],
  ['SPACE', 'SPACE(n)', 'String of n spaces.', 'varchar'],
  ['STR', 'STR(float, length, decimal)', 'Converts a number to character data.', 'varchar'],
  ['CONCAT', 'CONCAT(str1, str2, ...)', 'Concatenates values, treating NULL as empty string.', 'varchar / nvarchar'],
  ['CONCAT_WS', 'CONCAT_WS(separator, str1, str2, ...)', 'Concatenates with a separator, skipping NULLs.', 'varchar / nvarchar'],
  ['FORMAT', "FORMAT(value, format, culture)", '.NET-style formatting (e.g. FORMAT(GETDATE(), \'yyyy-MM-dd\')). Convenient but slow in bulk.', 'nvarchar'],
  ['QUOTENAME', "QUOTENAME(string, quote_char)", 'Returns a valid delimited identifier, e.g. [name].', 'nvarchar(258)'],
  ['ASCII', 'ASCII(char)', 'Code of the first character.', 'int'],
  ['CHAR', 'CHAR(code)', 'Character for an ASCII code.', 'char(1)'],
  ['NCHAR', 'NCHAR(code)', 'Unicode character for a code point.', 'nchar(1)'],
  ['UNICODE', 'UNICODE(nchar)', 'Code point of the first character.', 'int'],
  ['SOUNDEX', 'SOUNDEX(string)', 'Four-character phonetic code.', 'varchar(4)'],
  ['STRING_SPLIT', "STRING_SPLIT(string, separator)", 'Table-valued: splits a string into rows.', 'table (value)'],
  ['STRING_ESCAPE', "STRING_ESCAPE(string, 'json')", 'Escapes special characters for JSON.', 'nvarchar'],
  // Math
  ['ABS', 'ABS(x)', 'Absolute value.', 'same as input'],
  ['CEILING', 'CEILING(x)', 'Smallest integer >= x.', 'same as input'],
  ['FLOOR', 'FLOOR(x)', 'Largest integer <= x.', 'same as input'],
  ['ROUND', 'ROUND(x, decimals)', 'Rounds x to the given number of decimal places.', 'same as input'],
  ['SIGN', 'SIGN(x)', '-1, 0, or +1 depending on sign.', 'same as input'],
  ['SQRT', 'SQRT(x)', 'Square root.', 'float'],
  ['SQUARE', 'SQUARE(x)', 'x squared.', 'float'],
  ['POWER', 'POWER(a, b)', 'a raised to the power b.', 'same as a'],
  ['EXP', 'EXP(x)', 'e raised to x.', 'float'],
  ['LOG', 'LOG(x, base)', 'Natural log of x, or log to the given base.', 'float'],
  ['LOG10', 'LOG10(x)', 'Base-10 logarithm.', 'float'],
  ['PI', 'PI()', 'The constant π.', 'float'],
  ['RAND', 'RAND(seed)', 'Random float in [0, 1).', 'float'],
  ['DEGREES', 'DEGREES(radians)', 'Radians to degrees.', 'same as input'],
  ['RADIANS', 'RADIANS(degrees)', 'Degrees to radians.', 'same as input'],
  // Date / time
  ['GETDATE', 'GETDATE()', 'Current database server datetime.', 'datetime'],
  ['GETUTCDATE', 'GETUTCDATE()', 'Current UTC datetime.', 'datetime'],
  ['SYSDATETIME', 'SYSDATETIME()', 'Current datetime2 with more precision.', 'datetime2(7)'],
  ['SYSUTCDATETIME', 'SYSUTCDATETIME()', 'Current UTC datetime2.', 'datetime2(7)'],
  ['SYSDATETIMEOFFSET', 'SYSDATETIMEOFFSET()', 'Current datetimeoffset including time zone.', 'datetimeoffset(7)'],
  ['DATEADD', 'DATEADD(datepart, number, date)', 'Adds an interval to a date (e.g. DATEADD(day, 7, d)).', 'same as date'],
  ['DATEDIFF', 'DATEDIFF(datepart, start, end)', 'Count of datepart boundaries crossed between two dates.', 'int'],
  ['DATEDIFF_BIG', 'DATEDIFF_BIG(datepart, start, end)', 'Like DATEDIFF but returns bigint.', 'bigint'],
  ['DATENAME', 'DATENAME(datepart, date)', 'Name of the datepart as a string (e.g. month name).', 'nvarchar'],
  ['DATEPART', 'DATEPART(datepart, date)', 'Integer value of the datepart.', 'int'],
  ['DATETRUNC', 'DATETRUNC(datepart, date)', 'Truncates a date to the given precision (SQL Server 2022+).', 'same as date'],
  ['DAY', 'DAY(date)', 'Day of the month.', 'int'],
  ['MONTH', 'MONTH(date)', 'Month number.', 'int'],
  ['YEAR', 'YEAR(date)', 'Year number.', 'int'],
  ['EOMONTH', 'EOMONTH(date, months_to_add)', 'Last day of the month.', 'date'],
  ['DATEFROMPARTS', 'DATEFROMPARTS(year, month, day)', 'Builds a date from parts.', 'date'],
  ['DATETIMEFROMPARTS', 'DATETIMEFROMPARTS(y, m, d, h, mi, s, ms)', 'Builds a datetime from parts.', 'datetime'],
  ['TIMEFROMPARTS', 'TIMEFROMPARTS(h, mi, s, fractions, precision)', 'Builds a time from parts.', 'time'],
  ['SWITCHOFFSET', 'SWITCHOFFSET(datetimeoffset, timezone)', 'Changes the time-zone offset, preserving the UTC instant.', 'datetimeoffset'],
  ['ISDATE', 'ISDATE(expression)', '1 if the expression is a valid date.', 'int'],
  // Conversion
  ['CAST', 'CAST(expression AS type)', 'Converts a value to another data type.', 'target type'],
  ['CONVERT', 'CONVERT(type, expression, style)', 'Converts with an optional format style (e.g. 112 = yyyymmdd).', 'target type'],
  ['TRY_CAST', 'TRY_CAST(expression AS type)', 'CAST that returns NULL on failure instead of erroring.', 'target type or NULL'],
  ['TRY_CONVERT', 'TRY_CONVERT(type, expression, style)', 'CONVERT that returns NULL on failure.', 'target type or NULL'],
  ['PARSE', "PARSE(string AS type USING culture)", 'Parses a string to date/number using a culture.', 'target type'],
  // Logical / conditional
  ['COALESCE', 'COALESCE(value, ...)', 'First non-null argument.', 'highest-precedence argument type'],
  ['NULLIF', 'NULLIF(value1, value2)', 'NULL if the two values are equal, else value1.', 'same as value1'],
  ['ISNULL', 'ISNULL(check, replacement)', 'Replacement value when check is NULL.', 'same as check'],
  ['IIF', 'IIF(condition, true_value, false_value)', 'Inline if/else.', 'highest-precedence branch type'],
  ['CHOOSE', 'CHOOSE(index, val1, val2, ...)', 'Returns the item at the given 1-based index.', 'highest-precedence item type'],
  ['GREATEST', 'GREATEST(value, ...)', 'Largest of the arguments (SQL Server 2022+).', 'highest-precedence argument type'],
  ['LEAST', 'LEAST(value, ...)', 'Smallest of the arguments (SQL Server 2022+).', 'highest-precedence argument type'],
  // Window / ranking
  ['ROW_NUMBER', 'ROW_NUMBER() OVER (...)', 'Sequential row number within the partition.', 'bigint'],
  ['RANK', 'RANK() OVER (...)', 'Rank with gaps for ties.', 'bigint'],
  ['DENSE_RANK', 'DENSE_RANK() OVER (...)', 'Rank without gaps.', 'bigint'],
  ['NTILE', 'NTILE(buckets) OVER (...)', 'Splits rows into N ranked buckets.', 'bigint'],
  ['LAG', 'LAG(value, offset, default) OVER (...)', 'Value from a preceding row.', 'same as value'],
  ['LEAD', 'LEAD(value, offset, default) OVER (...)', 'Value from a following row.', 'same as value'],
  ['FIRST_VALUE', 'FIRST_VALUE(value) OVER (...)', 'Value from the first row of the window frame.', 'same as value'],
  ['LAST_VALUE', 'LAST_VALUE(value) OVER (...)', 'Value from the last row of the window frame.', 'same as value'],
  ['PERCENT_RANK', 'PERCENT_RANK() OVER (...)', 'Relative rank of the current row.', 'float'],
  ['CUME_DIST', 'CUME_DIST() OVER (...)', 'Cumulative distribution of the current row.', 'float'],
  ['PERCENTILE_CONT', 'PERCENTILE_CONT(fraction) WITHIN GROUP (ORDER BY expr) OVER (...)', 'Interpolated percentile.', 'float'],
  // JSON
  ['JSON_VALUE', "JSON_VALUE(json, '$.path')", 'Extracts a scalar value from JSON.', 'nvarchar(4000)'],
  ['JSON_QUERY', "JSON_QUERY(json, '$.path')", 'Extracts an object or array from JSON.', 'nvarchar(max)'],
  ['JSON_MODIFY', "JSON_MODIFY(json, '$.path', newValue)", 'Updates a value in a JSON string.', 'nvarchar(max)'],
  ['ISJSON', 'ISJSON(expression)', '1 if the string is valid JSON.', 'int'],
  ['OPENJSON', "OPENJSON(json, '$.path')", 'Table-valued: shreds JSON into rows and columns.', 'table'],
  // System / metadata
  ['NEWID', 'NEWID()', 'Random uniqueidentifier (GUID).', 'uniqueidentifier'],
  ['ISNUMERIC', 'ISNUMERIC(expression)', '1 if the expression can be converted to a numeric type.', 'int'],
  ['DB_NAME', 'DB_NAME(database_id)', 'Database name (current one when no argument).', 'nvarchar(128)'],
  ['OBJECT_ID', "OBJECT_ID('name')", 'Object id for a schema-scoped object name.', 'int'],
  ['OBJECT_NAME', 'OBJECT_NAME(object_id)', 'Object name for an object id.', 'sysname'],
  ['SCOPE_IDENTITY', 'SCOPE_IDENTITY()', 'Last identity value inserted in the current scope.', 'numeric(38,0)'],
  ['IDENT_CURRENT', "IDENT_CURRENT('table')", 'Last identity value generated for a table.', 'numeric(38,0)'],
  ['USER_NAME', 'USER_NAME(id)', 'Database user name.', 'nvarchar(128)'],
  ['SUSER_SNAME', 'SUSER_SNAME()', 'Login name of the current user.', 'nvarchar(128)'],
  ['HOST_NAME', 'HOST_NAME()', 'Workstation name of the client.', 'nvarchar(128)'],
  ['ERROR_MESSAGE', 'ERROR_MESSAGE()', 'Message text of the error that ran the CATCH block.', 'nvarchar(4000)'],
  ['ERROR_NUMBER', 'ERROR_NUMBER()', 'Error number inside a CATCH block.', 'int'],
  ['ERROR_LINE', 'ERROR_LINE()', 'Line number where the error occurred.', 'int'],
  ['HASHBYTES', "HASHBYTES('SHA2_256', data)", 'Hash of the input using the given algorithm.', 'varbinary(8000)'],
  ['CHECKSUM', 'CHECKSUM(expression, ...)', 'Hash value over its arguments, useful for change detection.', 'int'],
  ['COMPRESS', 'COMPRESS(expression)', 'GZIP-compresses data to varbinary.', 'varbinary(max)'],
  ['DECOMPRESS', 'DECOMPRESS(expression)', 'Decompresses data produced by COMPRESS.', 'varbinary(max)'],
];
