/**
 * Static, curated SQL intelligence data.
 * Kept as compact tuples so the bundled size stays tiny; CompletionItems
 * are built lazily on first use and cached (see completion.ts).
 */

/** [name, signature, one-line doc] */
export type FnDoc = readonly [string, string, string];

export const COMMON_KEYWORDS: string[] = [
  'SELECT', 'FROM', 'WHERE', 'GROUP BY', 'ORDER BY', 'HAVING', 'DISTINCT',
  'INSERT INTO', 'UPDATE', 'DELETE FROM', 'VALUES', 'SET',
  'INNER JOIN', 'LEFT JOIN', 'RIGHT JOIN', 'FULL OUTER JOIN', 'CROSS JOIN', 'ON',
  'AS', 'AND', 'OR', 'NOT', 'IN', 'EXISTS', 'BETWEEN', 'LIKE',
  'IS NULL', 'IS NOT NULL', 'ASC', 'DESC', 'UNION', 'UNION ALL', 'ANY', 'ALL',
  'CASE', 'WHEN', 'THEN', 'ELSE', 'END', 'WITH',
  'CREATE TABLE', 'ALTER TABLE', 'DROP TABLE', 'TRUNCATE TABLE', 'CREATE INDEX', 'CREATE VIEW',
  'PRIMARY KEY', 'FOREIGN KEY', 'REFERENCES', 'CONSTRAINT', 'DEFAULT', 'UNIQUE', 'CHECK',
  'BEGIN', 'COMMIT', 'ROLLBACK',
  'OVER', 'PARTITION BY', 'ROWS BETWEEN', 'UNBOUNDED PRECEDING', 'CURRENT ROW',
  'OFFSET', 'FETCH NEXT',
];

export const PG_KEYWORDS: string[] = [
  'LIMIT', 'ILIKE', 'RETURNING', 'LATERAL', 'USING',
  'ON CONFLICT', 'DO NOTHING', 'DO UPDATE', 'EXPLAIN', 'EXPLAIN ANALYZE',
  'VACUUM', 'ANALYZE', 'GENERATED ALWAYS AS IDENTITY', 'SERIAL', 'TABLESAMPLE',
];

export const MSSQL_KEYWORDS: string[] = [
  'TOP', 'OUTPUT', 'MERGE', 'GO', 'USE', 'EXEC', 'DECLARE',
  'PIVOT', 'UNPIVOT', 'CROSS APPLY', 'OUTER APPLY', 'WITH (NOLOCK)',
  'IDENTITY', 'IF EXISTS', 'PRINT',
];

/**
 * Single-word tokens that get auto-UPPERCASED as you type (see keywordCase.ts).
 * Deliberately keywords only — never function names.
 */
export const UPPERCASE_TOKENS: string[] = [
  'SELECT', 'FROM', 'WHERE', 'AND', 'OR', 'NOT', 'NULL', 'IS', 'IN', 'EXISTS',
  'BETWEEN', 'LIKE', 'ILIKE', 'AS', 'ON', 'JOIN', 'INNER', 'LEFT', 'RIGHT',
  'FULL', 'OUTER', 'CROSS', 'GROUP', 'BY', 'ORDER', 'HAVING', 'DISTINCT',
  'UNION', 'ALL', 'ANY', 'CASE', 'WHEN', 'THEN', 'ELSE', 'END', 'WITH',
  'INSERT', 'INTO', 'VALUES', 'UPDATE', 'SET', 'DELETE', 'CREATE', 'ALTER',
  'DROP', 'TABLE', 'INDEX', 'VIEW', 'PRIMARY', 'KEY', 'FOREIGN', 'REFERENCES',
  'CONSTRAINT', 'DEFAULT', 'UNIQUE', 'CHECK', 'ASC', 'DESC', 'LIMIT', 'OFFSET',
  'FETCH', 'NEXT', 'ROWS', 'ONLY', 'TOP', 'OVER', 'PARTITION', 'RETURNING',
  'LATERAL', 'USING', 'MERGE', 'DECLARE', 'BEGIN', 'COMMIT', 'ROLLBACK',
  'TRUNCATE', 'EXEC', 'USE', 'GO', 'IF', 'WHILE', 'APPLY', 'PIVOT', 'UNPIVOT',
];

export const PG_FUNCTIONS: FnDoc[] = [
  // Aggregates
  ['count', 'count(expression)', 'Number of input rows for which expression is not null; count(*) counts all rows.'],
  ['sum', 'sum(expression)', 'Sum of expression across all input rows.'],
  ['avg', 'avg(expression)', 'Average (arithmetic mean) of expression.'],
  ['min', 'min(expression)', 'Minimum value of expression.'],
  ['max', 'max(expression)', 'Maximum value of expression.'],
  ['array_agg', 'array_agg(expression)', 'Collects all input values into an array.'],
  ['string_agg', "string_agg(expression, delimiter)", 'Concatenates values into a string separated by delimiter.'],
  ['json_agg', 'json_agg(expression)', 'Aggregates values into a JSON array.'],
  ['jsonb_agg', 'jsonb_agg(expression)', 'Aggregates values into a JSONB array.'],
  ['json_object_agg', 'json_object_agg(key, value)', 'Aggregates key/value pairs into a JSON object.'],
  ['bool_and', 'bool_and(expression)', 'True if all input values are true.'],
  ['bool_or', 'bool_or(expression)', 'True if at least one input value is true.'],
  ['stddev', 'stddev(expression)', 'Sample standard deviation of the input values.'],
  ['variance', 'variance(expression)', 'Sample variance of the input values.'],
  ['percentile_cont', 'percentile_cont(fraction) WITHIN GROUP (ORDER BY expr)', 'Continuous percentile — interpolated value at the given fraction.'],
  ['percentile_disc', 'percentile_disc(fraction) WITHIN GROUP (ORDER BY expr)', 'Discrete percentile — first value whose position equals or exceeds the fraction.'],
  ['mode', 'mode() WITHIN GROUP (ORDER BY expr)', 'Most frequent input value.'],
  // String
  ['length', 'length(string)', 'Number of characters in string.'],
  ['char_length', 'char_length(string)', 'Number of characters in string.'],
  ['lower', 'lower(string)', 'Converts string to lower case.'],
  ['upper', 'upper(string)', 'Converts string to upper case.'],
  ['initcap', 'initcap(string)', 'Capitalizes the first letter of each word.'],
  ['trim', "trim([leading|trailing|both] chars from string)", 'Removes leading/trailing characters (spaces by default).'],
  ['ltrim', 'ltrim(string, chars)', 'Removes characters from the start of string.'],
  ['rtrim', 'rtrim(string, chars)', 'Removes characters from the end of string.'],
  ['btrim', 'btrim(string, chars)', 'Removes characters from both ends of string.'],
  ['lpad', 'lpad(string, length, fill)', 'Pads string on the left to length using fill.'],
  ['rpad', 'rpad(string, length, fill)', 'Pads string on the right to length using fill.'],
  ['substring', 'substring(string from start for count)', 'Extracts a substring (also substring(string, start, count)).'],
  ['substr', 'substr(string, start, count)', 'Extracts a substring.'],
  ['position', 'position(substring in string)', '1-based location of substring, 0 if not found.'],
  ['strpos', 'strpos(string, substring)', '1-based location of substring, 0 if not found.'],
  ['replace', 'replace(string, from, to)', 'Replaces all occurrences of a substring.'],
  ['translate', 'translate(string, from, to)', 'Replaces each character in from with the matching character in to.'],
  ['concat', 'concat(str1, str2, ...)', 'Concatenates arguments, ignoring NULLs.'],
  ['concat_ws', 'concat_ws(separator, str1, str2, ...)', 'Concatenates with separator, ignoring NULLs.'],
  ['split_part', 'split_part(string, delimiter, n)', 'Splits string on delimiter and returns the n-th field.'],
  ['left', 'left(string, n)', 'First n characters of string.'],
  ['right', 'right(string, n)', 'Last n characters of string.'],
  ['repeat', 'repeat(string, n)', 'Repeats string n times.'],
  ['reverse', 'reverse(string)', 'Reverses the string.'],
  ['regexp_replace', 'regexp_replace(string, pattern, replacement, flags)', 'Replaces substrings matching a POSIX regex.'],
  ['regexp_matches', 'regexp_matches(string, pattern, flags)', 'Returns captured substrings from a regex match (set-returning).'],
  ['regexp_split_to_array', 'regexp_split_to_array(string, pattern)', 'Splits string on a regex into an array.'],
  ['regexp_split_to_table', 'regexp_split_to_table(string, pattern)', 'Splits string on a regex into rows.'],
  ['format', "format(formatstr, args...)", 'sprintf-style string formatting (%s, %I identifier, %L literal).'],
  ['md5', 'md5(string)', 'MD5 hash of string as hex.'],
  ['to_hex', 'to_hex(number)', 'Converts a number to its hex representation.'],
  ['ascii', 'ascii(char)', 'Code point of the first character.'],
  ['chr', 'chr(code)', 'Character with the given code point.'],
  ['quote_ident', 'quote_ident(string)', 'Quotes a string for use as an identifier.'],
  ['quote_literal', 'quote_literal(value)', 'Quotes a value for use as a string literal.'],
  ['starts_with', 'starts_with(string, prefix)', 'True if string begins with prefix.'],
  // Math
  ['abs', 'abs(x)', 'Absolute value.'],
  ['ceil', 'ceil(x)', 'Smallest integer >= x.'],
  ['floor', 'floor(x)', 'Largest integer <= x.'],
  ['round', 'round(x, s)', 'Rounds x to s decimal places.'],
  ['trunc', 'trunc(x, s)', 'Truncates x toward zero to s decimal places.'],
  ['sign', 'sign(x)', '-1, 0, or +1 depending on the sign of x.'],
  ['sqrt', 'sqrt(x)', 'Square root.'],
  ['cbrt', 'cbrt(x)', 'Cube root.'],
  ['power', 'power(a, b)', 'a raised to the power b.'],
  ['exp', 'exp(x)', 'e raised to x.'],
  ['ln', 'ln(x)', 'Natural logarithm.'],
  ['log', 'log(b, x)', 'Logarithm of x to base b (log(x) is base 10).'],
  ['mod', 'mod(y, x)', 'Remainder of y / x.'],
  ['pi', 'pi()', 'The constant π.'],
  ['random', 'random()', 'Random value in [0, 1).'],
  ['degrees', 'degrees(radians)', 'Radians to degrees.'],
  ['radians', 'radians(degrees)', 'Degrees to radians.'],
  ['gcd', 'gcd(a, b)', 'Greatest common divisor.'],
  ['width_bucket', 'width_bucket(operand, low, high, count)', 'Bucket number for operand in an equal-width histogram.'],
  // Date / time
  ['now', 'now()', 'Current date and time (start of transaction).'],
  ['current_date', 'current_date → date', 'Current date (no parentheses).'],
  ['current_timestamp', 'current_timestamp → timestamptz', 'Current date and time (no parentheses).'],
  ['clock_timestamp', 'clock_timestamp()', 'Actual current time — changes within a statement.'],
  ['age', 'age(timestamp, timestamp)', 'Symbolic interval between two timestamps (or from now()).'],
  ['date_part', "date_part('field', source)", 'Extracts a subfield (year, month, dow, epoch, ...) as float.'],
  ['date_trunc', "date_trunc('field', source)", 'Truncates to the given precision (hour, day, month, ...).'],
  ['extract', 'extract(field from source)', 'Extracts a subfield from a date/time value.'],
  ['to_char', 'to_char(value, format)', 'Formats a timestamp/number as text (e.g. YYYY-MM-DD).'],
  ['to_date', 'to_date(text, format)', 'Parses text into a date using a format.'],
  ['to_timestamp', 'to_timestamp(text, format)', 'Parses text into a timestamp (or converts a Unix epoch).'],
  ['to_number', 'to_number(text, format)', 'Parses text into a numeric using a format.'],
  ['make_date', 'make_date(year, month, day)', 'Builds a date from parts.'],
  ['make_interval', 'make_interval(years, months, weeks, days, hours, mins, secs)', 'Builds an interval from parts.'],
  ['make_timestamp', 'make_timestamp(year, month, day, hour, min, sec)', 'Builds a timestamp from parts.'],
  ['generate_series', 'generate_series(start, stop, step)', 'Generates a set of values from start to stop (numbers or timestamps).'],
  ['pg_sleep', 'pg_sleep(seconds)', 'Pauses the current session.'],
  // Conditional
  ['coalesce', 'coalesce(value, ...)', 'First non-null argument.'],
  ['nullif', 'nullif(value1, value2)', 'NULL if the two values are equal, else value1.'],
  ['greatest', 'greatest(value, ...)', 'Largest of the arguments.'],
  ['least', 'least(value, ...)', 'Smallest of the arguments.'],
  // JSON
  ['to_json', 'to_json(anyelement)', 'Converts a value to JSON.'],
  ['to_jsonb', 'to_jsonb(anyelement)', 'Converts a value to JSONB.'],
  ['row_to_json', 'row_to_json(record)', 'Converts a row to a JSON object.'],
  ['json_build_object', 'json_build_object(key, value, ...)', 'Builds a JSON object from alternating key/value arguments.'],
  ['jsonb_build_object', 'jsonb_build_object(key, value, ...)', 'Builds a JSONB object from alternating key/value arguments.'],
  ['json_build_array', 'json_build_array(value, ...)', 'Builds a JSON array from arguments.'],
  ['jsonb_set', 'jsonb_set(target, path, new_value, create_missing)', 'Replaces the value at path in a JSONB document.'],
  ['jsonb_pretty', 'jsonb_pretty(jsonb)', 'Formats JSONB as indented text.'],
  ['jsonb_array_length', 'jsonb_array_length(jsonb)', 'Number of elements in the top-level JSONB array.'],
  ['jsonb_each', 'jsonb_each(jsonb)', 'Expands a JSONB object into key/value rows.'],
  ['jsonb_object_keys', 'jsonb_object_keys(jsonb)', 'Returns the keys of a JSONB object as rows.'],
  ['jsonb_extract_path_text', 'jsonb_extract_path_text(jsonb, path...)', 'Extracts a nested value as text.'],
  // Arrays
  ['array_length', 'array_length(array, dimension)', 'Length of the array in the given dimension.'],
  ['cardinality', 'cardinality(array)', 'Total number of elements in the array.'],
  ['array_append', 'array_append(array, element)', 'Appends an element to an array.'],
  ['array_cat', 'array_cat(array1, array2)', 'Concatenates two arrays.'],
  ['array_remove', 'array_remove(array, element)', 'Removes all occurrences of element.'],
  ['array_position', 'array_position(array, element)', 'Index of the first occurrence of element.'],
  ['array_to_string', 'array_to_string(array, delimiter)', 'Joins array elements into a string.'],
  ['string_to_array', 'string_to_array(string, delimiter)', 'Splits a string into an array.'],
  ['unnest', 'unnest(array)', 'Expands an array into rows.'],
  // Window
  ['row_number', 'row_number() OVER (...)', 'Sequential row number within the partition.'],
  ['rank', 'rank() OVER (...)', 'Rank with gaps for ties.'],
  ['dense_rank', 'dense_rank() OVER (...)', 'Rank without gaps.'],
  ['percent_rank', 'percent_rank() OVER (...)', 'Relative rank: (rank − 1) / (rows − 1).'],
  ['cume_dist', 'cume_dist() OVER (...)', 'Cumulative distribution of the current row.'],
  ['ntile', 'ntile(buckets) OVER (...)', 'Splits the partition into N ranked buckets.'],
  ['lag', 'lag(value, offset, default) OVER (...)', 'Value from a preceding row in the partition.'],
  ['lead', 'lead(value, offset, default) OVER (...)', 'Value from a following row in the partition.'],
  ['first_value', 'first_value(value) OVER (...)', 'Value from the first row of the window frame.'],
  ['last_value', 'last_value(value) OVER (...)', 'Value from the last row of the window frame.'],
  ['nth_value', 'nth_value(value, n) OVER (...)', 'Value from the n-th row of the window frame.'],
  // System / misc
  ['gen_random_uuid', 'gen_random_uuid()', 'Random UUID (v4).'],
  ['version', 'version()', 'PostgreSQL server version string.'],
  ['current_database', 'current_database()', 'Name of the current database.'],
  ['current_schema', 'current_schema()', 'Name of the current schema.'],
  ['current_user', 'current_user → name', 'Current user name (no parentheses).'],
  ['pg_typeof', 'pg_typeof(any)', 'Data type of the argument.'],
  ['pg_size_pretty', 'pg_size_pretty(bigint)', 'Formats bytes as a human-readable size.'],
  ['pg_total_relation_size', "pg_total_relation_size('table')", 'Total disk space used by a table, incl. indexes and TOAST.'],
  ['pg_database_size', "pg_database_size('name')", 'Disk space used by a database.'],
  ['cast', 'cast(expression AS type)', 'Converts a value to another data type (also expr::type).'],
];

export const MSSQL_FUNCTIONS: FnDoc[] = [
  // Aggregates
  ['COUNT', 'COUNT(expression)', 'Number of items in a group; COUNT(*) counts all rows.'],
  ['COUNT_BIG', 'COUNT_BIG(expression)', 'Like COUNT but returns bigint.'],
  ['SUM', 'SUM(expression)', 'Sum of all values in the expression.'],
  ['AVG', 'AVG(expression)', 'Average of the values in a group.'],
  ['MIN', 'MIN(expression)', 'Minimum value in the expression.'],
  ['MAX', 'MAX(expression)', 'Maximum value in the expression.'],
  ['STRING_AGG', "STRING_AGG(expression, separator)", 'Concatenates values with a separator (ORDER BY via WITHIN GROUP).'],
  ['STDEV', 'STDEV(expression)', 'Sample standard deviation.'],
  ['VAR', 'VAR(expression)', 'Sample variance.'],
  ['APPROX_COUNT_DISTINCT', 'APPROX_COUNT_DISTINCT(expression)', 'Fast approximate distinct count for big data.'],
  ['GROUPING', 'GROUPING(column)', '1 when the column is aggregated by ROLLUP/CUBE, else 0.'],
  ['CHECKSUM_AGG', 'CHECKSUM_AGG(expression)', 'Checksum of the values in a group.'],
  // String
  ['LEN', 'LEN(string)', 'Number of characters, excluding trailing spaces.'],
  ['DATALENGTH', 'DATALENGTH(expression)', 'Number of bytes used by the expression.'],
  ['LOWER', 'LOWER(string)', 'Converts to lower case.'],
  ['UPPER', 'UPPER(string)', 'Converts to upper case.'],
  ['LTRIM', 'LTRIM(string)', 'Removes leading spaces.'],
  ['RTRIM', 'RTRIM(string)', 'Removes trailing spaces.'],
  ['TRIM', "TRIM(characters FROM string)", 'Removes leading and trailing spaces (or given characters).'],
  ['SUBSTRING', 'SUBSTRING(string, start, length)', 'Extracts part of a string (1-based).'],
  ['CHARINDEX', 'CHARINDEX(substring, string, start)', '1-based position of substring, 0 if not found.'],
  ['PATINDEX', "PATINDEX('%pattern%', string)", 'Position of the first match of a pattern.'],
  ['REPLACE', 'REPLACE(string, from, to)', 'Replaces all occurrences of a substring.'],
  ['TRANSLATE', 'TRANSLATE(string, from_chars, to_chars)', 'Replaces characters one-for-one.'],
  ['STUFF', 'STUFF(string, start, length, replaceWith)', 'Deletes length chars at start and inserts replacement.'],
  ['LEFT', 'LEFT(string, n)', 'First n characters.'],
  ['RIGHT', 'RIGHT(string, n)', 'Last n characters.'],
  ['REPLICATE', 'REPLICATE(string, n)', 'Repeats string n times.'],
  ['REVERSE', 'REVERSE(string)', 'Reverses the string.'],
  ['SPACE', 'SPACE(n)', 'String of n spaces.'],
  ['STR', 'STR(float, length, decimal)', 'Converts a number to character data.'],
  ['CONCAT', 'CONCAT(str1, str2, ...)', 'Concatenates values, treating NULL as empty string.'],
  ['CONCAT_WS', 'CONCAT_WS(separator, str1, str2, ...)', 'Concatenates with a separator, skipping NULLs.'],
  ['FORMAT', "FORMAT(value, format, culture)", '.NET-style formatting (e.g. FORMAT(GETDATE(), \'yyyy-MM-dd\')). Convenient but slow in bulk.'],
  ['QUOTENAME', "QUOTENAME(string, quote_char)", 'Returns a valid delimited identifier, e.g. [name].'],
  ['ASCII', 'ASCII(char)', 'Code of the first character.'],
  ['CHAR', 'CHAR(code)', 'Character for an ASCII code.'],
  ['NCHAR', 'NCHAR(code)', 'Unicode character for a code point.'],
  ['UNICODE', 'UNICODE(nchar)', 'Code point of the first character.'],
  ['SOUNDEX', 'SOUNDEX(string)', 'Four-character phonetic code.'],
  ['STRING_SPLIT', "STRING_SPLIT(string, separator)", 'Table-valued: splits a string into rows.'],
  ['STRING_ESCAPE', "STRING_ESCAPE(string, 'json')", 'Escapes special characters for JSON.'],
  // Math
  ['ABS', 'ABS(x)', 'Absolute value.'],
  ['CEILING', 'CEILING(x)', 'Smallest integer >= x.'],
  ['FLOOR', 'FLOOR(x)', 'Largest integer <= x.'],
  ['ROUND', 'ROUND(x, decimals)', 'Rounds x to the given number of decimal places.'],
  ['SIGN', 'SIGN(x)', '-1, 0, or +1 depending on sign.'],
  ['SQRT', 'SQRT(x)', 'Square root.'],
  ['SQUARE', 'SQUARE(x)', 'x squared.'],
  ['POWER', 'POWER(a, b)', 'a raised to the power b.'],
  ['EXP', 'EXP(x)', 'e raised to x.'],
  ['LOG', 'LOG(x, base)', 'Natural log of x, or log to the given base.'],
  ['LOG10', 'LOG10(x)', 'Base-10 logarithm.'],
  ['PI', 'PI()', 'The constant π.'],
  ['RAND', 'RAND(seed)', 'Random float in [0, 1).'],
  ['DEGREES', 'DEGREES(radians)', 'Radians to degrees.'],
  ['RADIANS', 'RADIANS(degrees)', 'Degrees to radians.'],
  // Date / time
  ['GETDATE', 'GETDATE()', 'Current database server datetime.'],
  ['GETUTCDATE', 'GETUTCDATE()', 'Current UTC datetime.'],
  ['SYSDATETIME', 'SYSDATETIME()', 'Current datetime2 with more precision.'],
  ['SYSUTCDATETIME', 'SYSUTCDATETIME()', 'Current UTC datetime2.'],
  ['SYSDATETIMEOFFSET', 'SYSDATETIMEOFFSET()', 'Current datetimeoffset including time zone.'],
  ['DATEADD', 'DATEADD(datepart, number, date)', 'Adds an interval to a date (e.g. DATEADD(day, 7, d)).'],
  ['DATEDIFF', 'DATEDIFF(datepart, start, end)', 'Count of datepart boundaries crossed between two dates.'],
  ['DATEDIFF_BIG', 'DATEDIFF_BIG(datepart, start, end)', 'Like DATEDIFF but returns bigint.'],
  ['DATENAME', 'DATENAME(datepart, date)', 'Name of the datepart as a string (e.g. month name).'],
  ['DATEPART', 'DATEPART(datepart, date)', 'Integer value of the datepart.'],
  ['DATETRUNC', 'DATETRUNC(datepart, date)', 'Truncates a date to the given precision (SQL Server 2022+).'],
  ['DAY', 'DAY(date)', 'Day of the month.'],
  ['MONTH', 'MONTH(date)', 'Month number.'],
  ['YEAR', 'YEAR(date)', 'Year number.'],
  ['EOMONTH', 'EOMONTH(date, months_to_add)', 'Last day of the month.'],
  ['DATEFROMPARTS', 'DATEFROMPARTS(year, month, day)', 'Builds a date from parts.'],
  ['DATETIMEFROMPARTS', 'DATETIMEFROMPARTS(y, m, d, h, mi, s, ms)', 'Builds a datetime from parts.'],
  ['TIMEFROMPARTS', 'TIMEFROMPARTS(h, mi, s, fractions, precision)', 'Builds a time from parts.'],
  ['SWITCHOFFSET', 'SWITCHOFFSET(datetimeoffset, timezone)', 'Changes the time-zone offset, preserving the UTC instant.'],
  ['ISDATE', 'ISDATE(expression)', '1 if the expression is a valid date.'],
  // Conversion
  ['CAST', 'CAST(expression AS type)', 'Converts a value to another data type.'],
  ['CONVERT', 'CONVERT(type, expression, style)', 'Converts with an optional format style (e.g. 112 = yyyymmdd).'],
  ['TRY_CAST', 'TRY_CAST(expression AS type)', 'CAST that returns NULL on failure instead of erroring.'],
  ['TRY_CONVERT', 'TRY_CONVERT(type, expression, style)', 'CONVERT that returns NULL on failure.'],
  ['PARSE', "PARSE(string AS type USING culture)", 'Parses a string to date/number using a culture.'],
  // Logical / conditional
  ['COALESCE', 'COALESCE(value, ...)', 'First non-null argument.'],
  ['NULLIF', 'NULLIF(value1, value2)', 'NULL if the two values are equal, else value1.'],
  ['ISNULL', 'ISNULL(check, replacement)', 'Replacement value when check is NULL.'],
  ['IIF', 'IIF(condition, true_value, false_value)', 'Inline if/else.'],
  ['CHOOSE', 'CHOOSE(index, val1, val2, ...)', 'Returns the item at the given 1-based index.'],
  ['GREATEST', 'GREATEST(value, ...)', 'Largest of the arguments (SQL Server 2022+).'],
  ['LEAST', 'LEAST(value, ...)', 'Smallest of the arguments (SQL Server 2022+).'],
  // Window / ranking
  ['ROW_NUMBER', 'ROW_NUMBER() OVER (...)', 'Sequential row number within the partition.'],
  ['RANK', 'RANK() OVER (...)', 'Rank with gaps for ties.'],
  ['DENSE_RANK', 'DENSE_RANK() OVER (...)', 'Rank without gaps.'],
  ['NTILE', 'NTILE(buckets) OVER (...)', 'Splits rows into N ranked buckets.'],
  ['LAG', 'LAG(value, offset, default) OVER (...)', 'Value from a preceding row.'],
  ['LEAD', 'LEAD(value, offset, default) OVER (...)', 'Value from a following row.'],
  ['FIRST_VALUE', 'FIRST_VALUE(value) OVER (...)', 'Value from the first row of the window frame.'],
  ['LAST_VALUE', 'LAST_VALUE(value) OVER (...)', 'Value from the last row of the window frame.'],
  ['PERCENT_RANK', 'PERCENT_RANK() OVER (...)', 'Relative rank of the current row.'],
  ['CUME_DIST', 'CUME_DIST() OVER (...)', 'Cumulative distribution of the current row.'],
  ['PERCENTILE_CONT', 'PERCENTILE_CONT(fraction) WITHIN GROUP (ORDER BY expr) OVER (...)', 'Interpolated percentile.'],
  // JSON
  ['JSON_VALUE', "JSON_VALUE(json, '$.path')", 'Extracts a scalar value from JSON.'],
  ['JSON_QUERY', "JSON_QUERY(json, '$.path')", 'Extracts an object or array from JSON.'],
  ['JSON_MODIFY', "JSON_MODIFY(json, '$.path', newValue)", 'Updates a value in a JSON string.'],
  ['ISJSON', 'ISJSON(expression)', '1 if the string is valid JSON.'],
  ['OPENJSON', "OPENJSON(json, '$.path')", 'Table-valued: shreds JSON into rows and columns.'],
  // System / metadata
  ['NEWID', 'NEWID()', 'Random uniqueidentifier (GUID).'],
  ['ISNUMERIC', 'ISNUMERIC(expression)', '1 if the expression can be converted to a numeric type.'],
  ['DB_NAME', 'DB_NAME(database_id)', 'Database name (current one when no argument).'],
  ['OBJECT_ID', "OBJECT_ID('name')", 'Object id for a schema-scoped object name.'],
  ['OBJECT_NAME', 'OBJECT_NAME(object_id)', 'Object name for an object id.'],
  ['SCOPE_IDENTITY', 'SCOPE_IDENTITY()', 'Last identity value inserted in the current scope.'],
  ['IDENT_CURRENT', "IDENT_CURRENT('table')", 'Last identity value generated for a table.'],
  ['USER_NAME', 'USER_NAME(id)', 'Database user name.'],
  ['SUSER_SNAME', 'SUSER_SNAME()', 'Login name of the current user.'],
  ['HOST_NAME', 'HOST_NAME()', 'Workstation name of the client.'],
  ['ERROR_MESSAGE', 'ERROR_MESSAGE()', 'Message text of the error that ran the CATCH block.'],
  ['ERROR_NUMBER', 'ERROR_NUMBER()', 'Error number inside a CATCH block.'],
  ['ERROR_LINE', 'ERROR_LINE()', 'Line number where the error occurred.'],
  ['HASHBYTES', "HASHBYTES('SHA2_256', data)", 'Hash of the input using the given algorithm.'],
  ['CHECKSUM', 'CHECKSUM(expression, ...)', 'Hash value over its arguments, useful for change detection.'],
  ['COMPRESS', 'COMPRESS(expression)', 'GZIP-compresses data to varbinary.'],
  ['DECOMPRESS', 'DECOMPRESS(expression)', 'Decompresses data produced by COMPRESS.'],
];
